### ISSUE TITLE
French Fansub Update - Fall 2015

### ISSUE THREAD

**Issue by arekkuusu** [fansub/fansub.github.io#18]
seiryoku will sub Concrete Revolutio, One Punch Man, Mobile Suit Gundam: Tekketsu no Orphans, Heavy Object, Sakurako-san no Ashimoto ni wa Shitai ga Umatteiru, and Osomatsu-san.

**Comment by fansub** [comment]
:+1: Thanks!

**Comment by fansub** [comment]
fix by 925170b0579779a2ea76661ac09bb2f934a225c7
