### ISSUE TITLE
Not the correct font

### ISSUE THREAD

**Issue by fansub** [fansub/fansub.github.io#5]
https://github.com/fansub/fansub.github.io/blob/2effd8c6ad6055ab479508296cbc25631f9dafa5/fr/archives.html#L44 has the style https://github.com/fansub/fansub.github.io/blob/2effd8c6ad6055ab479508296cbc25631f9dafa5/stylesheets/archive_deco.css#L2,L3,L8 but a @font-face in src relative seems fail.

**Comment by KasaiDot** [comment]
Tout semble "ok" de mon côté.
Ps : ajouttez le label "fermé" ou "closed"

**Comment by fansub** [comment]
yes, seems to be corrected.

**Comment by fansub** [comment]
On Firefox, when I want to know the font of the japanese here: https://fansub.github.io/fr/archives.html , it's not Kodomo Rounded like I want.

**Comment by fansub** [comment]
I'll remove it because so much work.
